name: Push to Vercel

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    # container: pandoc/latex

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      

      - name: Create vercel.json file if TARGET_VERCEL_JSON is present
        if: steps.check_vercel_json.outputs.vercel_json_present == 'true'
        run: |
          JSON='{
            "version": 2,
            "builds": [
              {
                "src": "app.js",
                "use": "@vercel/node"
              }
            ],
            "routes": [
              {
                "src": "/(.*)",
                "dest": "app.js"
              }
            ],
            "installCommand": "npm install"
          }'
          echo "$JSON" > vercel.json

      # - name: Set environment variables and push to another repository
      #   run: |
      #     echo "TARGET_GIT_TOKEN=${{ fromJson(steps.send_post_request.outputs.response).data.TARGET_GIT_TOKEN }}" >> $GITHUB_ENV
      #     echo "TARGET_GIT_USER=${{ fromJson(steps.send_post_request.outputs.response).data.TARGET_GIT_USER }}" >> $GITHUB_ENV
      #     echo "TARGET_GIT_REPO=${{ fromJson(steps.send_post_request.outputs.response).data.TARGET_GIT_REPO }}" >> $GITHUB_ENV

      # - name: Pushes to another repository
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ env.TARGET_GIT_TOKEN }}
      #   with:
      #     source-directory: '.'
      #     destination-github-username: ${{ env.TARGET_GIT_USER }}
      #     destination-repository-name: ${{ env.TARGET_GIT_REPO }}
      #     user-email: carles3@pina.cat
      #     target-branch: main